version: "3"
x-app: &app
  build:
    context: .
    dockerfile: ./docker/Dockerfile.dev
  image: avely-dev:0.0.22

x-dapp: &dapp
  <<: *app
  stdin_open: true
  tty: true
  volumes: &volumes
    - ./:/dapp:cached
    - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
    - ~/.ssh:/root/.ssh
    - ~/.bash_history:/root/.bash_history
  environment: &environment
    EDITOR: vi
  security_opt:
    - seccomp:unconfined
  cap_add:
    - SYS_PTRACE
  depends_on:
    - zilliqa_server
  networks:
      default:

services:
  runner:
    <<: *dapp
    command: /bin/bash
    entrypoint: ""
    ports: []

  zilliqa_server:
    image: zilliqa/zilliqa-isolated-server:latest
    #volumes:
    #  - zilliqa_server:/zilliqa/persistence
    environment:
      MANUAL_MODE: "true"
    #  MODE: "load"
    ports:
      - '5555:5555'

  devex:
    image: zilliqa/devex
    ports:
      - '5557:80'
    volumes:
      - ./devex/networks.json:/usr/share/nginx/html/networks.json
    depends_on:
      - zilliqa_server

volumes:
  zilliqa_server:
