version: "3.9"
x-app: &app
  build:
    context: .
    dockerfile: ./docker/Dockerfile.dev
  image: avely-dev:0.0.22

x-dapp: &dapp
  <<: *app
  stdin_open: true
  tty: true
  volumes: &volumes
    - ./:/dapp:cached
    - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
    - ~/.ssh:/root/.ssh
    - ~/.bash_history:/root/.bash_history
    - go-modules:/root/go/pkg/mod
  environment: &environment
    EDITOR: vi
  security_opt:
    - seccomp:unconfined
  cap_add:
    - SYS_PTRACE
  depends_on:
    - zilliqa_server
  networks:
    default:

services:
  runner:
    <<: *dapp
    container_name: runner.avely
    command: /bin/bash
    entrypoint: ""
    ports: []

  zilliqa_server:
    image: zilliqaisolatedserver:932
    container_name: zilliqa.avely
    #volumes:
    #  - zilliqa_server:/zilliqa/persistence
    volumes:
      - ./docker/isolated-server-accounts.json:/zilliqa/boot.json
    ports:
      - 5555:5555
    environment:
      - MANUAL_MODE=true
    #  - T=0
    #  MODE: "load"

  devex:
    image: zilliqa/devex
    container_name: devex.avely
    ports:
      - "5557:80"
    volumes:
      - ./devex/networks.json:/usr/share/nginx/html/networks.json
    depends_on:
      - zilliqa_server

volumes:
  zilliqa_server:
  go-modules:
