ARG BASE_IMAGE=zilliqa/scilla:v0.13.5

FROM ${BASE_IMAGE}

ENV LANG=C.UTF-8
ENV OCAML_VERSION=4.12.0
ENV SCILLA_VERSION=0.13.5

RUN mkdir -p /dapp
WORKDIR /dapp

COPY ./ /dapp

# Scilla gets installed here
ENV PATH="/scilla/0/_build/install/default/bin:${PATH}"
ENV SCILLA_HOME="/scilla/0/_build/install/default/lib/scilla"

RUN apt-get update && apt-get install -y software-properties-common

# Install Golang
RUN add-apt-repository ppa:longsleep/golang-backports \
    && apt-get update \
    && apt-get -y install golang-go \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install dev & debug tools
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y gdb git vim \
		&& apt-get clean \
		&& rm -rf /var/cache/apt/archives/* \
		&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
		&& truncate -s 0 /var/log/*log
