name: CI & CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: watchers
  IMAGE_VERSION: latest

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ezil/avely-dev:0.0.1
    env:
      CI: "1"
    steps:
    - uses: actions/checkout@v2

    - name: Go fmt
      run: |
        output=$(gofmt -d -l -s .)
        echo $output
        test -z "$output"

    - id: go-cache-paths
      run: |
        echo "::set-output name=go-build::$(go env GOCACHE)"
        echo "::set-output name=go-mod::$(go env GOMODCACHE)"

    # Cache go build cache, used to speedup go test
    - name: Go Build Cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.go-cache-paths.outputs.go-build }}
        key: ${{ runner.os }}-go-build-${{ hashFiles('go.sum') }}

    - name: Go Mod Cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.go-cache-paths.outputs.go-mod }}
        key: ${{ runner.os }}-go-mod-${{ hashFiles('go.sum') }}

    - name: Prepare env file
      run: |
        cp .env.example .env.local
        echo "API_HTTPURL = https://zilliqa-isolated-server.zilliqa.com/" >> .env.local
        cat .env.local

    - name: Run tests
      run: |
        cat .env.local
        go run tests/main.go

  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:

    - name: Log in to registry
      # This is where you will update the PAT to GITHUB_TOKEN
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - uses: actions/checkout@v3

    - name: Build Image
      run: docker build --rm=false -f docker/Dockerfile.prod --tag $IMAGE_NAME .

    - name: push image to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        echo IMAGE_ID=$IMAGE_ID
        echo IMAGE_VERSION=$IMAGE_VERSION
        docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_VERSION
        docker push $IMAGE_ID:$IMAGE_VERSION
